language: python
python:
  - "3.6"
env:
  global:
    - CC_TEST_REPORTER_ID=7b2a8d89ec2d09fea972c4475e21285a4e7d055c72db35d026f263f9a8027395
cache:
  directories:
    - $HOME/miniconda
before_install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ -d $HOME/miniconda/bin ]]; then
      echo "Miniconda already installed!";
    else
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi;
      bash miniconda.sh -b -p $HOME/miniconda;
    fi
  - . /home/travis/miniconda/etc/profile.d/conda.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - sudo apt-get install tree
install:
  # Useful for debugging any issues with conda
  - conda info -a
  - git clone https://github.com/hlibbabii/fastai $HOME/fastai-fork
  - cd $HOME/fastai-fork
  - conda env create -f environment.yml
  - conda activate fastai
  - export PYTHONPATH="$HOME/fastai-fork:$PYTHONPATH"
  - echo "PYTHONPATH is now $PYTHONPATH"
  - cd $TRAVIS_BUILD_DIR
  - conda env update -f environment.yml
  - cd $HOME
  - git clone https://github.com/hlibbabii/jsons
  - pip install -e jsons
  - echo "Showing dir structure"
  - tree -L 2
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - cd $TRAVIS_BUILD_DIR
  - coverage run -m unittest discover -v -s "tests" -p "*.py"
  - coverage report -m
  - coverage xml
  - echo "Running integration tests pipeline..."
  - chmod +x integration-tests/run.sh
  - integration-tests/run.sh
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
# blocklist
branches:
  except:
  - readme
