name: fastai
channels:
- conda-forge
dependencies:
- fastcluster
- google-api-python-client
- httplib2
- deepdiff
- python-levenshtein
- oauth2client
- pip:
  - typing_inspect
  - cupy-cuda91
  - coverage